services:
  janus:
    platform: linux/${TARGETARCH:-amd64}
    build: 
      context: ./janus
    ports:
      - "8188:8188"  # WebSocket
      - "8088:8088"  # REST API
      - "6002:6002/udp"  # RTP port for video processor
      - "6001:6001/udp"  # RTCP port
      - "8004:8004/udp"  # RTP output port
      - "20000-20050:20000-20050/udp"  # Smaller WebRTC port range
    volumes:
      - ./janus/conf/janus.plugin.videoroom.jcfg:/usr/local/etc/janus/janus.plugin.videoroom.jcfg
      - ./janus/conf/janus.plugin.streaming.jcfg:/usr/local/etc/janus/janus.plugin.streaming.jcfg
      - ./janus/conf/janus.jcfg:/usr/local/etc/janus/janus.jcfg
    networks:
      - video_network

  video_processor:
    platform: linux/${TARGETARCH:-amd64}
    build:
      context: ./processor
    networks:
      - video_network
    depends_on:
      - janus
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(socket.AF_INET,socket.SOCK_DGRAM); s.bind(('0.0.0.0',6002))"]
      interval: 30s
      timeout: 10s
      retries: 3
    cap_add:
      - NET_ADMIN
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - UDP_BUFFER_SIZE=26214400

networks:
  video_network:
    driver: bridge 